config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :units
  devise_for :users
  root "home#index"
  resources :expenses
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, Expense
         #can :read, Unit
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  paginates_per 20
end

app/models/unit.rb
class Unit < ApplicationRecord
  enum :unit_type, [:Departamento, :Bodega, :Estacionamiento]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :admin) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :admin) }
  end
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :alert => exception.message
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: %[index show]
  before_action :set_expense, only: %i[ show edit update destroy ]

  # GET /expenses or /expenses.json
  def index
    @q = Expense.ransack(params[:q])
    @expenses = @q.result(distinct: true).page(params[:page])
    #@expenses = Expense.all
  end

  # GET /expenses/1 or /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to expense_url(@expense), notice: "Expense was successfully created." }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: "Expense was successfully updated." }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: "Expense was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expense_params
      params.require(:expense).permit(:supplier, :month, :year, :document_type, :document_date, :category, :amount, :description, :payment_method, :payment_number)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!, except: %[index show]
  def index
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: %[index show]
  before_action :set_unit, only: %i[ show edit update destroy ]

  # GET /units or /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1 or /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units or /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to unit_url(@unit), notice: "Unit was successfully created." }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1 or /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to unit_url(@unit), notice: "Unit was successfully updated." }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1 or /units/1.json
  def destroy
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url, notice: "Unit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def unit_params
      params.require(:unit).permit(:name, :unit_type, :alicuota)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>">
  <p>
    <strong>Supplier:</strong>
    <%= expense.supplier %>
  </p>

  <p>
    <strong>Month:</strong>
    <%= expense.month %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= expense.year %>
  </p>

  <p>
    <strong>Document type:</strong>
    <%= expense.document_type %>
  </p>

  <p>
    <strong>Document date:</strong>
    <%= expense.document_date %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= expense.category %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= expense.amount %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= expense.description %>
  </p>

  <p>
    <strong>Payment method:</strong>
    <%= expense.payment_method %>
  </p>

  <p>
    <strong>Payment number:</strong>
    <%= expense.payment_number %>
  </p>

</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense) do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :supplier, style: "display: block" %>
    <%= form.text_field :supplier %>
  </div>

  <div>
    <%= form.label :month, style: "display: block" %>
    <%= form.text_field :month %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.text_field :year %>
  </div>

  <div>
    <%= form.label :document_type, style: "display: block" %>
    <%= form.text_field :document_type %>
  </div>

  <div>
    <%= form.label :document_date, style: "display: block" %>
    <%= form.date_field :document_date %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :payment_method, style: "display: block" %>
    <%= form.text_field :payment_method %>
  </div>

  <div>
    <%= form.label :payment_number, style: "display: block" %>
    <%= form.text_field :payment_number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/_search_form.html.erb
<%= search_form_for @q do |f| %>
  <%= f.select :year_cont, ["2022", "2023", "2024", "2025"] %>
  <%= f.select :month_cont, ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"] %>
  <%= f.search_field :description_cont, placeholder: "descripción" %>
  <%= f.submit "Buscar" %>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Show this expense", @expense %> |
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Egresos</h1>
<%= render "search_form" %>
<%= link_to "Egresos", expenses_path %>

<% if can? :create, new_expense_path %> | 
<%= link_to "Nuevo Egreso", new_expense_path %>
<% end %>

<%= paginate @expenses %>
<div id="expenses">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Año</th>
        <th>Mes</th>
        <th>Categoría</th>
        <th>Proveedor</th>
        <th>Tipo Documento</th>
        <th>Fecha Documento</th>
        <th>Monto ($)</th>
        <th>Descripción</th>
        <th>Forma de Pago</th>
        <th>N° Pago</th>
        <th></th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.year %></td>
        <td><%= expense.month %></td>
        <td><%= expense.category %></td>
        <td><%= expense.supplier %></td>
        <td><%= expense.document_type %></td>
        <td><%= expense.document_date %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.description %></td>
        <td><%= expense.payment_method %></td>
        <td><%= expense.payment_number %></td>
        <td><%= link_to "Ver", expense %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<%= paginate @expenses %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>

<div>
  <%= link_to "Back to expenses", expenses_path %>
  <% if can? :update, @expense %>
    <%= link_to "Edit this expense", edit_expense_path(@expense) %> |
  <% end %>

  <% if can? :destroy, @expense %>
    <%= button_to "Destroy this expense", @expense, method: :delete %>
  <% end %>
</div>

app/views/home/index.html.erb
<h1>Gestión de Edificios</h1>
<p>Aplicación de Registro de Gastos Comunes</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestionEdificios</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <% if user_signed_in? %>
         <p><%= current_user.name %> | <%= link_to 'Cerrar Sesión', destroy_user_session_path, data: { "turbo-method": :delete } %></p>
        <%= link_to 'Inicio', root_path %> | 

        <% if can? :read, Expense %>
          <%= link_to 'Egresos', expenses_path %> | 
        <% end %>

        <% if can? :read, Unit %>
          <%= link_to 'Unidades', units_path %> | 
        <% end %>

          <%= link_to 'Editar Mi Usuario', edit_user_registration_path %>
      <% end %>

    <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

app/views/units/_form.html.erb
<%= form_with(model: unit) do |form| %>
  <% if unit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
        <% unit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-3">
    <%= form.label :name, "Nombre",  style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="mt-3">
    <%= form.label :unit_type,"Tipo de Unidad",  style: "display: block" %>
    <%= form.select :unit_type, Unit.unit_types.keys %>
  </div>

  <div class="mt-3">
    <%= form.label :alicuota, "Alícuota",  style: "display: block" %>
    <%= form.text_field :alicuota %>
  </div>

  <div class="mt-3">
    <%= form.submit "Guardar" %>
  </div>
<% end %>

app/views/units/_unit.html.erb
<div id="<%= dom_id unit %>">
  <p>
    <strong>Nombre:</strong>
    <%= unit.name %>
  </p>

  <p>
    <strong>Tipo de Unidad:</strong>
    <%= unit.unit_type %>
  </p>

  <p>
    <strong>Alícuota:</strong>
    <%= unit.alicuota %>
  </p>

</div>

app/views/units/edit.html.erb
<h1>Editar Unidad</h1>

<%= render "form", unit: @unit %>

<br>

<div>
  <%= link_to "Ver", @unit %> | 
  <%= link_to "Unidades", units_path %>
</div>

app/views/units/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Units</h1>

<% if can? :create, new_unit_path %>
<%= link_to "Nueva Unidad", new_unit_path %>
<% end %>
<div id="units">
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Tipo Unidad</th>
      <th>Alícuota</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @units.each do |unit| %>
    <tr>
      <td><%= unit.name %></td>
      <td><%= unit.unit_type%></td>
      <td><%= unit.alicuota %></td>
      <td><%= link_to "Ver", unit %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/units/new.html.erb
<h1>Nueva Unidad</h1>

<%= render "form", unit: @unit %>

<br>

<div>
  <%= link_to "Unidades", units_path %>
</div>

app/views/units/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @unit %>

<div>
  <%= link_to "Unidades", units_path %> | 
  <% if can? :update, @unit %>
    <%= link_to "Editar", edit_unit_path(@unit) %> |
  <% end %>

  <% if can? :destroy, @unit %>
    <%= button_to "Eliminar", @unit, method: :delete %>
  <% end %>

</div>